language: node_js
node_js: 
  - "8"
dist: trusty
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pnew_password
  - sudo service mysql restart
  - mysql -e schema.sql
env: 
  - NODE_ENV=ci
cache:
  directories:
    - node_modules
    - client/node_modules
install: 
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
