language: node_js
node_js: 
  - "8"
dist: trusty
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - mysql -e schema.sql
env: 
  - NODE_ENV=ci
cache:
  directories:
    - node_modules
    - client/node_modules
install: 
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
